version: '3.8'

services:
  backend:
    build: ./services/backend
    command: python manage.py
    volumes:
      - ./services/backend/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
volumes:
  postgres_data: