openapi: 3.0.0
info:
  title: Manager APIs.
  description: |-
    - Employee APIs
      - show all Employees
      - create new Employee
      - update Employee info.
      - delete Employee
  contact:
    name: 'Eyab Ghifari'
    email: eyab.m.g@gmail.com
  version: 0.1.9
servers:
  - url: /manager
tags:
  - name: Employee
    description: Everything about Employee

paths:
  /employee:
    get:
      tags:
        - Employee
      summary: Returns a list of all Employees.
      operationId: controllers.employee_api.get_employees
      responses:
        '200':
          description: A JSON array of Employees info.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/employee_info'
        '400':
          description: Error Bad Request
    post:
      tags:
        - Employee
      summary: Creates a Employee.
      operationId: controllers.employee_api.post_employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/employee_info'

      responses:
        '201':
          description: Created Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/employee_info'
        '400':
          description: Error Bad Request
  /employee/{emp_id}:
    get:
      tags:
        - Employee
      summary: Returns a Employee by ID.
      operationId: controllers.employee_api.show_employee_info
      parameters:
        - name: emp_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Found
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/employee_info'
        '404':
          description: Employee Not Found
        '400':
          description: Error Bad Request
    put:
      summary: update info of an Employee.
      operationId: controllers.employee_api.update_employee_info
      tags:
        - Employee
      parameters:
        - name: emp_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/employee_info'
      responses:
        '201':
          description: Updated Successfully
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/employee_info'
        '404':
          description: Employee Not Found
        '400':
          description: Error Bad Request


components:
  schemas:
    employee_info:
      title: info. of the Employee
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 'Ahmad Ahmad'
        phone_number:
          type: string
          example: '0596581120'
        date_of_birth:
          type: string
          format: date
          example: '1990-03-12'
        address:
          type: string
          example: 'Ramallah-Palestine'
        join_date:
          type: string
          format: date
          example: '2022-09-01'
        role:
          type: string
          example: 'cashier'
        status:
          type: string
          enum:
            - 'Active'
            - 'Deactivated'
          example: 'Active'
      required:
        - name
        - phone_number
        - date_of_birth
        - join_date
        - role